# Genetic Algorithm for solving the p-median problem from the Shell AI Hackathon

In [3]:
from pymoo.optimize import minimize

1. Problem
2. Algorithm
3. Stop criteria

## 1. Problem Definition

The **capacitated p-median problem** is a well-known optimization problem in operations research. It involves selecting *p* facilities from a set of potential locations to minimize the total distance between the facilities and the demand points (or customers) they serve. The problem is often used in facility location planning, where the goal is to determine the optimal location of facilities such as warehouses, hospitals, or schools to serve a given population. 

The problem is NP-hard, meaning that it is computationally infeasible to solve for large instances using exact methods. Therefore, heuristic and metaheuristic algorithms such as genetic algorithms are often used to find approximate solutions.

![Alt text](image.png)

#### Example:

*Medians* $= \{1,4\}$

Vertex | 1 | 2 | 3 | 4 | 5 | $\dots$ | n-1 | n
--- | --- | --- | --- |--- |--- |--- |--- |---
Median | -1 | 4 | 5 | -1 | 1 | $\dots$ | $m_{n-1}$|$m_n$



In [7]:
from pymoo.core.problem import Problem
from pymoo.problems.single.knapsack import Knapsack
import numpy as np
import pandas as pd

In [106]:
def load_distance_matrix():
    return pd.read_csv('dataset/Distance_Matrix.csv').drop('Unnamed: 0', axis=1)
def load_biomass():
    return pd.read_csv('dataset/Biomass_History.csv')

In [102]:
def cost_of_transportation(x, B, D):
    return np.sum(B @ (D*x))

In [3]:


def create_problem_data(num_harvesting_sites, num_warehouses, B, D, C, a=0.001, b=1):

    # create the objective function
    cost_of_transportation = np.sum(x * B.reshape(-1, 1) * D)
    cost_of_underutilization = np.sum(C - np.sum(x, axis=0))
    objective_function = a * cost_of_transportation + b * cost_of_underutilization

    return objective_function

def cost_of_transportation(x, B, D):
    return np.sum(x * B.reshape(-1, 1) * D)


class ProblemWrapper(Problem):
    def __init__(self, B, D, p):
        self.D = D
        self.B = B
        self.p = p
        super().__init__(n_var=1, n_obj=1, n_ieq_constr=2, 
                         n_eq_constr=1, xl=0, xu=1, vtype=int)

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = cost_of_transportation(x, self.B, self.D)
        out["G"] = np.sum(np.diag(x)) - self.p
        out["H"] = np.sum(x, axis=1) - 1
        out["I"] = np.sum



        

SyntaxError: incomplete input (2610931522.py, line 23)

In [114]:
# D is a distance matrix
# B is a demand matrix

medians = np.array([0])

D = np.array([[0, 1, 2], 
              [1, 0, 3], 
              [2, 3, 0]])

B = np.array([2, 2, 3])

x = np.array([[1, 0, 0], 
              [1, 0, 0], 
              [0, 0, 1]])

cost_of_transportation(x, B, D)

2

In [119]:
# sum the diagonal using numpy
np.sum(x, axis=0)

array([2, 0, 1])

In [84]:
B

array([2, 2, 3])

In [76]:
x

array([[1, 0, 0],
       [1, 1, 1],
       [0, 0, 1]])

In [71]:
D * x

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [45]:
D

array([[0, 1, 2],
       [1, 0, 3],
       [2, 3, 0]])

In [32]:
B.shape

(3,)

In [24]:
x.shape

(3,)

In [14]:
D

array([[1, 2, 3],
       [4, 5, 6]])